#!/usr/bin/env python3
"""Generate recipes/INDEX.md and recipes/index.json from recipe files.

usage: build_index.py [RECIPES_DIR]   (default ~/kitchen/recipes)

Recipes with errors are still indexed (so nothing silently disappears) but
are marked, and the script exits 1 so you notice. Run lint_recipes.py for detail.
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import DEFAULT_RECIPES, fmt_duration, load_all, load_vocab, parse_duration  # noqa: E402


def to_record(r):
    m = r.meta
    return {
        "title": m.get("title", r.path.stem),
        "path": r.rel,
        "category": r.category,
        "tags": [t.lower() for t in m.get("tags", [])] if isinstance(m.get("tags"), list) else [],
        "servings": int(m["servings"]) if str(m.get("servings", "")).isdigit() else None,
        "prep_min": parse_duration(m.get("prep")),
        "cook_min": parse_duration(m.get("cook")),
        "total_min": r.total_min(),
        "source": m.get("source"),
        "rating": int(m["rating"]) if str(m.get("rating", "")).isdigit() else None,
        "last_made": m.get("last_made"),
        "ingredients": sorted({i.normalized for i in r.ingredients if i.normalized}),
        "ingredient_lines": [i.raw[2:] for i in r.ingredients],
        "has_errors": bool(r.errors),
    }


def md_table(records):
    lines = [
        "# Recipe index",
        "",
        "Generated by `build_index.py`. Do not edit; edit the recipes and rerun.",
        "",
        "| Title | Category | Tags | Total | Servings | Rating | Last made |",
        "|:--|:--|:--|:--|:--|:--|:--|",
    ]
    for rec in sorted(records, key=lambda x: (x["category"], x["title"].lower())):
        title = f"[{rec['title']}]({rec['path']})"
        if rec["has_errors"]:
            title += " (lint errors)"
        lines.append(
            "| {t} | {c} | {tags} | {tot} | {s} | {r} | {lm} |".format(
                t=title,
                c=rec["category"],
                tags=", ".join(rec["tags"]),
                tot=fmt_duration(rec["total_min"]),
                s=rec["servings"] if rec["servings"] is not None else "",
                r=rec["rating"] if rec["rating"] is not None else "",
                lm=rec["last_made"] or "",
            )
        )
    lines.append("")
    lines.append(f"{len(records)} recipe(s).")
    return "\n".join(lines) + "\n"


def main(argv):
    root = Path(argv[1]).expanduser() if len(argv) > 1 else DEFAULT_RECIPES
    if not root.is_dir():
        print(f"error: recipes directory not found: {root}", file=sys.stderr)
        return 2
    vocab = load_vocab()
    recipes = load_all(root, vocab)
    records = [to_record(r) for r in recipes]
    (root / "INDEX.md").write_text(md_table(records), encoding="utf-8")
    (root / "index.json").write_text(
        json.dumps({"recipes": records}, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    bad = sum(1 for r in records if r["has_errors"])
    print(f"indexed {len(records)} recipe(s) -> {root / 'INDEX.md'}, {root / 'index.json'}")
    if bad:
        print(f"{bad} recipe(s) have lint errors; run lint_recipes.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
